### ISSUE TITLE
Page overlays on iPhone

### ISSUE THREAD

**Issue by kevbite** [dotnetsheff/dotnetsheff#11]
Text on iPhones does not fit correctly.

![_nbskkv5](https://user-images.githubusercontent.com/5544715/30208040-adb66084-9489-11e7-9c0f-fb8cc3135a27.jpg)

**Comment by mcastre** [comment]
hello @kevbite! I'd like to help you out on this one!

**Comment by kevbite** [comment]
Hello @mcastre thanks for helping out, I'll take a look at this later on today!

**Comment by kevbite** [comment]
Thanks for sort this, all merged in!
