### ISSUE TITLE
Add new sponsor to website

### ISSUE THREAD

**Issue by kevbite** [dotnetsheff/dotnetsheff#13]
We've got a new sponsor and need to add the logo to our website.

Sponsor: JetBrains
Sponsoring: Free giveaway licenses
Images: https://www.jetbrains.com/company/press/

**Comment by kevbite** [comment]
This is a fairly simple update so I've labeled this for `hacktoberfest`

**Comment by gravitydestroyer** [comment]
On it

**Comment by ranjanbinwani** [comment]
Implemented PR #14

**Comment by kevbite** [comment]
Sorry @ranjanbinwani but @gravitydestroyer already claimed this before you PR. Thanks guys for helping out though! very much appreciated!
