### ISSUE TITLE
Restyle main page so that we don't show a massive list of past events

### ISSUE THREAD

**Issue by kevbite** [dotnetsheff/dotnetsheff#6]
We're loading all the past events at the moment on to the home page.

Could do with moving these to another page or having just a snippet of each one in a grid?

**Comment by SFoskitt** [comment]
Your past events appear to be currently hard coded in your home page index.htm.  But the functions necessary to retrieve past events from Meetup.com is in main.js and work great.  I will remove the hard coded past events from index.htm and setup the previous events to load dynamically from the API.  I'll send you a pull request which displays 4 past events and will give you instruction how to change this number if you want to.

**Comment by kevbite** [comment]
Hello. Thanks for helping out with this change - very much appreciated.

The hard coded ones were before we had meetup.com page then we then transitioned to use meetup and just left the old ones hanging around.

Will look at PR and merge in!

**Comment by kevbite** [comment]
All merge in, and can be seen live at http://dotnetsheff.co.uk/.

Thanks for giving back to the community!
