### ISSUE TITLE
Integrate videos on website

### ISSUE THREAD

**Issue by kevbite** [dotnetsheff/dotnetsheff#8]
Would be good to get the videos of the events up on our main website.
- https://pusher.com/sessions/meetup/dotnetsheff/building-scalable-and-resilient-web-apps-with-microsoft-azure
- https://pusher.com/sessions/meetup/dotnetsheff/introduction-to-azure-service-fabric
- https://pusher.com/sessions/meetup/dotnetsheff/become-a-bot-builder-with-microsoft-bot-framework
- https://pusher.com/sessions/meetup/dotnetsheff/topshelf-the-smart-way-to-build-windows-services
- https://pusher.com/sessions/meetup/dotnetsheff/enchilada
- https://pusher.com/sessions/meetup/dotnetsheff/aspnet-nodejs-javascript-services
- https://pusher.com/sessions/meetup/dotnetsheff/ddd-a-la-carte
- https://pusher.com/sessions/meetup/dotnetsheff/from-0-to-cross-platform-mobile-apps-faster-than-you-can-say-xamarin-forms
- https://pusher.com/sessions/meetup/dotnetsheff/net-blub-frameworks-beyond-microsoft

details on integrating videos can be found here - https://wistia.com/doc/popover-customization#popover_embeds

**Comment by kevbite** [comment]
Added to rebrand branch.

**Comment by SuperDevGuru** [comment]
Please look at this site in process of development. And let me know if it is what you are searching for.
If yes, then you can reference my git repository 'StreamingServer'.
Thank you.
